<a href="https://colab.research.google.com/github/andrewluzan/first_repository/blob/main/submitted_HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.random.rand(10)
print(vector)
print('Its shape:',vector.shape)

[0.74546334 0.78494478 0.30328161 0.14876933 0.60464296 0.46510374
 0.36033744 0.68391909 0.30883926 0.86498168]
Its shape: (10,)


In [3]:
# Creation of matrix
A = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]])

print("Matrix A:")
print(A)
print('Its shape:', A.shape)

Matrix A:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Its shape: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [4]:
vector = vector + 10
rounded_vector = np.round(vector, 2)

print(rounded_vector)

[10.75 10.78 10.3  10.15 10.6  10.47 10.36 10.68 10.31 10.86]


In [5]:
A = A * 2

print("Matrix A multiplied by 2:")
print(A)

Matrix A multiplied by 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [6]:
vector_square = vector * vector

print(vector_square)

[115.46498241 116.31503398 106.15761185 102.99751898 112.45845241
 109.5183962  107.33659178 114.14612721 106.2721669  118.04782685]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [7]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [12]:
result_matrix = np.dot(B, A)
display(result_matrix)
result_matrix_2 = np.dot(result_matrix,C)
display(result_matrix_2)
result_matrix_3 = np.dot(result_matrix,D)
display(result_matrix_3)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

array([[0.5202],
       [0.2846]])

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [27]:
#1
result_matrix_T = result_matrix.T
display(result_matrix_T)

array([[0.232 , 0.3061, 0.1393],
       [0.1627, 0.4867, 0.2261],
       [0.2145, 0.633 , 0.294 ]])

In [38]:
#2
vector_T = vector.T
display(vector)
display(vector_T)
print('There is no difference between vector and vector_T')

array([20.95057778, 20.74477519, 20.01426506, 20.69546993, 20.08305906,
       20.21646313, 20.89164204, 20.02666098, 20.65663843, 20.87902248])

array([20.95057778, 20.74477519, 20.01426506, 20.69546993, 20.08305906,
       20.21646313, 20.89164204, 20.02666098, 20.65663843, 20.87902248])

There is no difference between vector and vector_T


In [51]:
#3
column_vector = np.expand_dims(vector, axis=1)
print(column_vector)
print(vector)

print('column_vector is transported to its oringinal vector')

[[20.95057778]
 [20.74477519]
 [20.01426506]
 [20.69546993]
 [20.08305906]
 [20.21646313]
 [20.89164204]
 [20.02666098]
 [20.65663843]
 [20.87902248]]
[20.95057778 20.74477519 20.01426506 20.69546993 20.08305906 20.21646313
 20.89164204 20.02666098 20.65663843 20.87902248]
column_vector is transported to its oringinal vector


In [50]:
#4
column_vector_T = column_vector.T
print(column_vector_T)

print('column_vector_T shape:',column_vector_T.shape)
print('column_vector shape:',column_vector.shape)

[[20.95057778 20.74477519 20.01426506 20.69546993 20.08305906 20.21646313
  20.89164204 20.02666098 20.65663843 20.87902248]]
column_vector_T shape: (1, 10)
column_vector_T shape: (10, 1)
